name: Java with Nexus Repository

on:
  workflow_dispatch:
  push:
    branches:
      - all  
   

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
         ref: 'ado_new'
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build  Maven 
      run: mvn package --file pom.xml
    - name: Deploy to Azure Artifacts
      run: mvn deploy -s ./settings.xml -Denforcer.skip=true
