name: Build and Deploy Java App to AWS EC2

on:
  push:
    branches:
      - main  # Trigger the pipeline when code is pushed to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest  # This will run on an Ubuntu VM in GitHub Actions
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set Up Java and Maven in GitHub Actions
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # OpenJDK distribution
          java-version: '17'       # Set the version of Java
          
      - name: Build with Maven
        run: mvn clean package -DskipTests  # Build the Java application (skip tests)
        
